### ISSUE TITLE
erd1skgcxgrqey32adjmlgslyyr2lqsl63k6crygl6rpf469xqddsr0qfhred7

### ISSUE THREAD

**Issue by Hosein1371** [multiversx/mx-battleofyields-site#258]
*Bug at farms page, not showing all of the assets:*

Firstly,On the farms page when I refresh it either shows my EGLD-MEX farm, or EGLD-BUSD farm, but not both at the same time even if I did stake on both?

Second, I've used the Stake now tools on testnet-wallet.elrond to stake some xEGLD, chose an active stake provider but then my xEGLD disapeared on the testnet wallet, my total stake shows 0 xEGLD.
Third, I am not able to swap from MEX to BUSD, as it is shown in the picture bellow.

Overall, A good project with the potential of improving and being one of the highest deeveloped projects. And also a suggestion, Put a tab to show the portfolio of all assets that are in the portfolio... with performance evolution...which there is no.

I am over the moon and can not wait to see the developments and improvements.

Best wishes,

![355DF72D-26EB-4E2B-B33C-4FD7975DFF6D](https://user-images.githubusercontent.com/90721362/133318665-80acbdcf-693c-48ff-a935-e3d061d66f26.jpeg)

**Comment by rxdhwan** [comment]
Regarding your issue #2 and #3. 

You lost your xEGLD because you staked it to staking nodes and not on Maiar DEX. The purpose of the xEGLD was to provide liquidity & test on Maiar DEX.

There is only one pair for MEX right now on the testnet. EGLD-MEX. So if you want to convert your MEX to BUSD, you have to convert it to EGLD first. 

- Community member.
